//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SolarApplication
{
    using System;
    using System.Collections.Generic;
    
    public partial class device
    {
        public int ID { get; set; }
        public string Name { get; set; }
        public Nullable<int> DimensionL { get; set; }
        public Nullable<int> DimensionW { get; set; }
        public Nullable<float> MaxVoltage { get; set; }
        public Nullable<float> MaxWattage { get; set; }
        public Nullable<int> DeviceTypeID { get; set; }
        public Nullable<int> MeterID { get; set; }
    
        public virtual devicetype devicetype { get; set; }
        public virtual meter meter { get; set; }
    }
}
