//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SolarApplication
{
    using System;
    using System.Collections.Generic;
    
    public partial class forecast
    {
        public forecast()
        {
            this.readings = new HashSet<reading>();
        }
    
        public System.DateTime ForecastDate { get; set; }
        public int WeatherTypeID { get; set; }
        public float Tempreature { get; set; }
        public float Humidity { get; set; }
        public float Wind { get; set; }
    
        public virtual weathertype weathertype { get; set; }
        public virtual ICollection<reading> readings { get; set; }
    }
}
