//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SolarApplication
{
    using System;
    using System.Collections.Generic;
    
    public partial class meter
    {
        public meter()
        {
            this.devices = new HashSet<device>();
            this.readings = new HashSet<reading>();
        }
    
        public int ID { get; set; }
        public string Name { get; set; }
        public int TypeID { get; set; }
    
        public virtual ICollection<device> devices { get; set; }
        public virtual metertype metertype { get; set; }
        public virtual ICollection<reading> readings { get; set; }
    }
}
