//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SolarApplication
{
    using System;
    using System.Collections.Generic;
    
    public partial class metertype
    {
        public metertype()
        {
            this.meters = new HashSet<meter>();
        }
    
        public int ID { get; set; }
        public string Type { get; set; }
    
        public virtual ICollection<meter> meters { get; set; }
    }
}
