//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SolarApplication
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class SolarDBEntities : DbContext
    {
        public SolarDBEntities()
            : base("name=SolarDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<device> devices { get; set; }
        public DbSet<devicetype> devicetypes { get; set; }
        public DbSet<forecast> forecasts { get; set; }
        public DbSet<meter> meters { get; set; }
        public DbSet<metertype> metertypes { get; set; }
        public DbSet<reading> readings { get; set; }
        public DbSet<readingtype> readingtypes { get; set; }
        public DbSet<weathertype> weathertypes { get; set; }
    }
}
