//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SolarApplication
{
    using System;
    using System.Collections.Generic;
    
    public partial class reading
    {
        public int ID { get; set; }
        public int MeterID { get; set; }
        public Nullable<System.DateTime> ForecastID { get; set; }
        public Nullable<int> ReadingTypeID { get; set; }
        public double readValue { get; set; }
        public System.DateTime readTime { get; set; }
    
        public virtual forecast forecast { get; set; }
        public virtual meter meter { get; set; }
        public virtual readingtype readingtype { get; set; }
    }
}
