//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SolarApplication
{
    using System;
    using System.Collections.Generic;
    
    public partial class weathertype
    {
        public weathertype()
        {
            this.forecasts = new HashSet<forecast>();
        }
    
        public int ID { get; set; }
        public string Weather { get; set; }
    
        public virtual ICollection<forecast> forecasts { get; set; }
    }
}
